VM_IP_RECORDS = '/qnap-vm.txt'
QCS_AUTOMATION_MASTER_CONF = 'qcs_automation_master_conf'
OVIRT_ENGINE_IP = '192.168.103.39'
OVIRT_ENGINE_UNAME = 'admin@internal'
OVIRT_ENGINE_PASS = 'master@123'
CLUSTER_NAME = 'newcl'
TEMPLATE_NAME = 'automation-template'
TEMPLATE_DS = 'data1'
